name: "Firmware CI Device Runner"
description:
  "GitHub action that schedules a firmware run on a real device connected to
  Azure IoT hub that runs a self-hosted GitHub Actions runner"
inputs:
  device id:
    description: "ID of the device the firmware belongs to (client ID)"
    required: true
  app version:
    description:
      "The version string to use for the app. This is used with the FOTA test."
    required: true
  azure credentials:
    description: "Azure credentials as JSON string"
    required: true
  azure location:
    description:
      "Location (region) of the nRF Asset Tracker instance the device connects
      to"
    required: true
  azure resource group:
    description: "Resource group of of the nRF Asset Tracker instance"
    required: true
  app name:
    description: "App name of the nRF Asset Tracker instance"
    required: true
  hex file:
    description: "The location of the firmware to flash"
    required: false
    default: firmware.hex
  fota file:
    description: "The location of the firmware file to use for the FOTA test"
    required: false
    default: fota-upgrade.bin
  abort on:
    description:
      "Abortion criteria for the Firmware CI runner, will be split by newlines."
    required: false
  end on:
    description:
      "End criteria for the Firmware CI runner, will be split by newlines."
    required: false
  target:
    description: "Target board to use"
    default: "nrf9160dk_nrf9160ns"
    required: false
  network:
    description: "Network to use"
    default: "ltem"
    required: false
  sec tag:
    description: "SecTag to use for credentials"
    default: "11"
    required: false
  timeout in minutes:
    description: "Timeout for job completion in minutes"
    default: "10"
    required: false
  certificate location:
    description: "Location where to read and write certificates"
    default: "./certficates"
    required: false
outputs:
  connected:
    description: "Whether the device connected."

runs:
  using: "node12"
  main: "build/index.js"
